import { Poppins } from "next/font/google";
import "../globals.css";

import SessionProvider from "../../../providers/session-provider";
import Navbar from "@/components/molecules/navbar";
import Footer from "@/components/molecules/footer";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          {children}
          <Footer/>
        </SessionProvider>
      </body>
    </html>
  );
}
