import { Inter } from "next/font/google";
import "../globals.css";
import SessionProvider from "../../../providers/session-provider";
import Navbar from "@/components/molecules/navbar";
import BottomNavigation from "@/components/molecules/bottom-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          {children}
          <BottomNavigation/>
        </SessionProvider>
      </body>
    </html>
  );
}
